#ifndef DIALOGPOINT_GLOBAL_H
#define DIALOGPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIALOGPOINT_LIBRARY)
#  define DIALOGPOINTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIALOGPOINTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIALOGPOINT_GLOBAL_H
